print("Hello World!")
print('   Sufi Baba')
print(' * *       * *')
print('*    *   *    *')
print('*      *      *')
print(' *           *')
print('   *       *')
print('     *   *')
print('       *')